-- 코드를 입력하세요
SELECT DATE_FORMAT(a.SALES_DATE,'%Y-%m-%d') as SALES_DATE,a.PRODUCT_ID,a.USER_ID,a.SALES_AMOUNT
from ONLINE_SALE a
where YEAR(a.SALES_DATE)='2022' and MONTH(a.SALES_DATE)=3
union all
SELECT DATE_FORMAT(b.SALES_DATE,'%Y-%m-%d')as SALES_DATE,b.PRODUCT_ID,NULL as USER_ID,b.SALES_AMOUNT
from OFFLINE_SALE b
where YEAR(b.SALES_DATE)='2022' and MONTH(b.SALES_DATE)=3
order by SALES_DATE,PRODUCT_ID,USER_ID
